# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppRegPanelmixPMLE <- function(bs, ys, xs, zs, mu0s, sigma0s, m, p, t, an, maxit = 2000L, ninits = 10L, tol = 1e-8, tau = 0.5, h = 0L, k = 0L) {
    .Call(`_NormalRegPanelMixture_cppRegPanelmixPMLE`, bs, ys, xs, zs, mu0s, sigma0s, m, p, t, an, maxit, ninits, tol, tau, h, k)
}

cppRegPanelmixPMLEAR1 <- function(bs, ys, xs, zs, ys0, xs0, zs0, mu0s, sigma0s, mu00s, sigma00s, m, p, t, an, maxit = 2000L, ninits = 10L, tol = 1e-8, tau = 0.5, h = 0L, k = 0L) {
    .Call(`_NormalRegPanelMixture_cppRegPanelmixPMLEAR1`, bs, ys, xs, zs, ys0, xs0, zs0, mu0s, sigma0s, mu00s, sigma00s, m, p, t, an, maxit, ninits, tol, tau, h, k)
}

cppnormalpanelmixPMLE <- function(bs, ys, zs, mu0s, sigma0s, m, p, t, an, maxit = 2000L, ninits = 10L, tol = 1e-8, tau = 0.5, h = 0L, k = 0L, psih = 0L) {
    .Call(`_NormalRegPanelMixture_cppnormalpanelmixPMLE`, bs, ys, zs, mu0s, sigma0s, m, p, t, an, maxit, ninits, tol, tau, h, k, psih)
}

