# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppRegPanelmixPMLE <- function(bs, ys, xs, zs, mu0s, sigma0s, m, p, t, an, maxit = 2000L, ninits = 10L, tol = 1e-8, tau = 0.5, h = 0L, k = 0L, epsilon = 0.05) {
    .Call(`_NormalRegPanelMixture_cppRegPanelmixPMLE`, bs, ys, xs, zs, mu0s, sigma0s, m, p, t, an, maxit, ninits, tol, tau, h, k, epsilon)
}

logistic_regression <- function(X, y, alpha, iterations) {
    .Call(`_NormalRegPanelMixture_logistic_regression`, X, y, alpha, iterations)
}

cppRegPanelmixPMLEAR1 <- function(bs, ys, xs, zs, zinits, mu0s, sigma0s, m, p, t, an, maxit = 2000L, ninits = 10L, tol = 1e-8, tau = 0.5, h = 0L, k = 0L, epsilon = 0.05) {
    .Call(`_NormalRegPanelMixture_cppRegPanelmixPMLEAR1`, bs, ys, xs, zs, zinits, mu0s, sigma0s, m, p, t, an, maxit, ninits, tol, tau, h, k, epsilon)
}

cppnormalpanelmixPMLE <- function(bs, ys, zs, mu0s, sigma0s, m, p, t, an, maxit = 2000L, ninits = 10L, tol = 1e-8, tau = 0.5, h = 0L, k = 0L, psih = 0L, epsilon = 0.05) {
    .Call(`_NormalRegPanelMixture_cppnormalpanelmixPMLE`, bs, ys, zs, mu0s, sigma0s, m, p, t, an, maxit, ninits, tol, tau, h, k, psih, epsilon)
}

